services:
  ollama:
    build:
      context: .
      dockerfile: ollama-service.Dockerfile
    container_name: ollama_service
    ports:
      - "11434:11434"
    hostname: ollama
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ''
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  fastapi:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  ollama_models:
    driver: local
